# Generated by Django 2.0.6 on 2018-06-24 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='프로필 pk')),
                ('profile_picture', models.FileField(null=True, upload_to='assets/images/', verbose_name='프로필 사진')),
                ('is_receiving_notification', models.BooleanField(default=True, verbose_name='푸시 알림 받는지 여부')),
                ('profile_of_user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='해당 프로필의 유저')),
            ],
            options={
                'verbose_name': '프로필',
                'verbose_name_plural': '프로필들',
                'db_table': 'profiles',
            },
        ),
    ]
