# Generated by Django 2.0.6 on 2018-07-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180706_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default=None, null=True, upload_to='profile_pictures/', verbose_name='프로필 사진'),
        ),
    ]
