# Generated by Django 2.0.6 on 2018-06-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180625_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=None, max_length=8, unique=True, verbose_name='닉네임'),
            preserve_default=False,
        ),
    ]
