# Generated by Django 2.0.6 on 2018-06-26 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_of_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='해당 프로필의 유저'),
        ),
    ]
