# Generated by Django 2.0.6 on 2018-06-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_of_user',
            new_name='user',
        ),
    ]
