# Generated by Django 2.0.6 on 2018-06-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20180627_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_of_user',
            new_name='user',
        ),
    ]
