# Generated by Django 2.0.6 on 2018-07-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='slug',
            field=models.SlugField(
                allow_unicode=True, default='asdf', max_length=20, verbose_name='파티 라벨'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='party',
            name='title',
            field=models.CharField(max_length=20, verbose_name='파티 제목'),
        ),
    ]
