# Generated by Django 2.0.6 on 2018-06-25 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180625_2012'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='participants',
            field=models.ManyToManyField(db_table='participants', limit_choices_to={True, 'is_active'}, related_name='participants', to='profiles.Profile', verbose_name='파티 참가자'),
        ),
        migrations.AddField(
            model_name='party',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=None, max_length=25, verbose_name='파티 라벨'),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to='profiles.Profile', verbose_name='파티 주최자'),
        ),
    ]
