# Generated by Django 2.0.6 on 2018-06-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_auto_20180625_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='slug',
        ),
        migrations.AlterField(
            model_name='party',
            name='current_people',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='현재 참여 인원'),
        ),
    ]
