# Generated by Django 2.0.6 on 2018-07-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_auto_20180702_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='participants',
            field=models.ManyToManyField(db_table='participants', related_name='participants', to='profiles.Profile', verbose_name='파티 참가자'),
        ),
    ]
