# Generated by Django 2.0.6 on 2018-07-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_auto_20180706_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, verbose_name='파티 라벨'),
        ),
    ]
