# Generated by Django 2.0.6 on 2018-06-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=None, max_length=10, verbose_name='댓글 라벨'),
        ),
    ]
