# Generated by Django 2.0.6 on 2018-07-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180703_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, verbose_name='댓글 라벨'),
        ),
    ]
