# Generated by Django 2.0.6 on 2018-07-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(default='token', editable=False,
                                   max_length=300, verbose_name='FCM 토큰'),
            preserve_default=False,
        ),
    ]
