# Generated by Django 2.0.6 on 2018-07-20 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_auto_20180715_1551'),
        ('notifications', '0002_remove_notification_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='text',
        ),
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.CharField(max_length=100, null=True, verbose_name='알림 내용'),
        ),
        migrations.AddField(
            model_name='notification',
            name='party',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parties.Party', verbose_name='알림과 연관된 파티'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=None, editable=False, max_length=100, unique=True, verbose_name='알림 라벨'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='title', max_length=30, verbose_name='알림 제목'),
            preserve_default=False,
        ),
    ]
