# Generated by Django 2.0.6 on 2018-07-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='slug',
        ),
    ]
